### ISSUE TITLE
POI Report: user should not directly enter the reporting process when not logged in

### ISSUE THREAD

**Issue by linyc0817** [CAMPUS-NYCU/smart-campus#20]
User can enter reporting process without log in now, but they will face error when they click the add report button. Meanwhile, no error log is displayed, which will cause confusion. 

![Image](https://github.com/CAMPUS-NYCU/smart-campus/assets/32840701/f5d43043-f3e1-4548-93bc-586721a1646a)

**Comment by y-c-wang** [comment]
Thanks for pointing out. I will take this work item.
